mv ./doc.kml ./hrcpwtna6222.kml
sed -i.bu 's/<href>/<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./hrcpwtna6222.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./0/0/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./1/0/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./1/1/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/0/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/0/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/1/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/1/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/1/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/1/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/1/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/1/7.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/10/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/10/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/10/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/10/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/10/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/10/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/10/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/11/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/11/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/11/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/11/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/12/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/2/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/2/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/2/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/2/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/2/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/2/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/2/7.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/3/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/3/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/3/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/3/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/3/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/3/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/3/7.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/4/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/4/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/4/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/4/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/4/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/4/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/4/7.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/5/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/5/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/5/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/5/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/5/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/5/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/5/7.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/6/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/6/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/6/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/6/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/6/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/6/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/6/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/7/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/7/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/7/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/7/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/7/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/7/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/7/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/8/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/8/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/8/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/8/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/8/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/8/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/8/6.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/9/0.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/9/1.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/9/2.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/9/3.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/9/4.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/9/5.kml
sed -i.bu 's/<href>..\/..\//<href>https:\/\/raw.githubusercontent.com\/dnaperman\/hrcpwtna6222\/main\//g' ./4/9/6.kml